[project]
name = "parrot"
requires-python = ">=3.14"

[tool.ruff]
line-length = 150
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "A",
    "C4",
    "UP",
    "SIM",
    "RET",
    "RUF",
    "ASYNC",
    "DTZ",
    "FA",
    "ISC",
    "PIE",
    "PGH",
    "PT",
    "T10",
    "T20",
    "EM",
    "G",
    "LOG",
    "PTH",
    "PERF",
    "PL",
]

ignore = [
    "E501",  # Line too long
    "PLR0913",  # Too many arguments
    "ASYNC109",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pylint]
max-positional-args = 9

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "PLR2004",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.pyright]
include = ["src", "tests"]
typeCheckingMode = "basic"
pythonVersion = "3.14"
venvPath = "."
venv = ".venv"
reportUnnecessaryTypeIgnoreComment = "warning"