ALL_ENDPOINTS = [
    "android",
    "angular",
    "api-security",
    "aspnet-core",
    "aws",
    "backend",
    "blockchain",
    "code-review",
    "computer-science",
    "cpp",
    "cyber-security",
    "design-system",
    "devops",
    "docker",
    "flutter",
    "frontend",
    "frontend-performance",
    "full-stack",
    "golang",
    "graphql",
    "guides",
    "java",
    "javascript",
    "kubernetes",
    "link-groups",
    "mongodb",
    "nodejs",
    "postgresql-dba",
    "prompt-engineering",
    "python",
    "qa",
    "react",
    "react-native",
    "software-architect",
    "software-design-architecture",
    "spring-boot",
    "system-design",
    "tests.py",
    "typescript",
    "ux-design",
    "videos",
    "vue",
]

FIRST_HALF_ENDPOINTS = ALL_ENDPOINTS[: len(ALL_ENDPOINTS) // 2]
SECOND_HALF_ENDPOINTS = ALL_ENDPOINTS[len(ALL_ENDPOINTS) // 2 :]
